language: go
go:
  - "1.10"
services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

before_install:
  - mysql -u root --password="" < test/test-user.sql
  - mysql -u root --password="" < test/sakila-schema.sql
  - mysql -u root --password="" < test/sakila-data.sql
